version: "3"

networks:
  app-network:
    driver: bridge

services:
  todo-backend:
    image: todo-backend
    container_name: todo-backend
    build:
      context: ./todo-backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1
    networks:
      - app-network

  todo-frontend:
    image: todo-frontend
    container_name: todo-frontend
    build:
      context: ./todo-frontend
      dockerfile: prod.Dockerfile
    depends_on:
      - todo-backend
    restart: always
    ports:
      - 3000:3000
    networks:
      - app-network
# Add more containers below (nginx, postgres, etc.)
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname

