version: "3"

networks:
  app-network:
    driver: bridge

services:
  todo-backend:
    image: todo-backend
    container_name: todo-backend
    build:
      context: ./todo-backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1,todo-backend
    networks:
      - app-network

  todo-frontend:
    image: todo-frontend
    container_name: todo-frontend
    build:
      context: ./todo-frontend
      dockerfile: prod.Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - todo-backend
    restart: always
    ports:
      - 3000:3000
    networks:
      - app-network

  reverse_proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
      - todo-backend
      - todo-frontend
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${NGINX_EXTERNAL_PORT}:${NGINX_INTERNAL_PORT}
    networks:
      - app-network
